/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in normal installs and kept here so the
// initial scaffold type-checks before the first local `next dev` run.
